config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'players#index'
  resources :players
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/player.rb
class Player < ApplicationRecord
  after_create_commit { broadcast_prepend_to 'players' }
  after_update_commit { broadcast_replace_to 'players' }
  after_destroy_commit { broadcast_remove_to 'players' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.create(player_params)
    respond_to do |format|
      if @player.save
        format.turbo_stream do
        end
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@player, partial: "players/form", locals: { player: @player }), status: :unprocessable_entity }
      end
    end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update(player_params)
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@player, partial: "players/form", locals: { player: @player }), status: :unprocessable_entity }
      end
    end
  end


   def destroy
    @player = Player.find(params[:id])
    respond_to do |format|
      if @player.destroy
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@player, partial: "players/form", locals: { player: @player }), status: :unprocessable_entity }
      end
    end
  end

  private

  def player_params
    params.require(:player).permit(:name, :runs)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CricketTeamManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
     <%= turbo_include_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-5 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/players/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Player Form</title>
</head>
<body>

<div class="container">
  <h1>Player Form</h1>

  <%= form_with(model: player, local: true, data: { turbo_action: "submit->players#create" }) do |form| %>
    <div class="form-group">
      <div class="input-field">
        <%= form.label :name %>
        <%= form.text_field :name, required: true %>
      </div>

      <div class="input-field">
        <%= form.label :runs %>
        <%= form.text_field :runs, required: true %>
      </div>

      <div class="submit-button">
        <%= form.submit player.new_record? ? "Add Player" : "Update Player" %>
      </div>
    </div>

    <script>
      document.addEventListener('turbo:submit-end', function(event) {
        if (event.detail.success) {
          if (<%= player.new_record? %>) {
            event.target.reset();
          }
        }
      });
    </script>
  <% end %>
</div>
</body>
</html>

app/views/players/_player.html.erb
<%= turbo_frame_tag dom_id(player) do %>
  <div  >
    <div>
      <h2 ><%= player.name %></h2>
      <p ><%= player.runs %></p>
    </div>
    <div>
      <%= link_to "Edit", edit_player_path(player) %>
      <%= link_to "Delete", player_path(player), data: { turbo_method: :delete, turbo_action: "click->players#destroy" } %>
      </div>
  </div>
<% end %>

app/views/players/edit.html.erb
<%= turbo_frame_tag dom_id(@player) do %>
  <%= render 'form', player: @player %>
<% end %>

app/views/players/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Players</title>
</head>
<body>

<div class="container">
  <h1>Players</h1>

  <%= turbo_frame_tag 'players' do %>
    <%= render @players %>
  <% end %>

  <%= turbo_stream_from "players" %>

  <%= turbo_frame_tag 'new_player' do %>
    <%= link_to "Add Player", new_player_path %>
  <% end %>
</div>
</body>
</html>

app/views/players/new.html.erb
<%= turbo_frame_tag 'new_player' do %>
  <%= render 'form', player: @player %>
<% end %>